[package]
name = "logic_function_optimizations"
version = "1.0.0"
edition = "2021"
authors = ["Petr Portnov <portnovpv@student.bmstu.ru>"]
repository = "https://github.com/BMSTU-ICS-CS-2019/logic-function-optimizations"

[profile.release]
panic = "abort"
strip = true
lto = true
codegen-units = 1
